python simple_test.py ex0
python simple_test.py ex1
python simple_test.py ex2
python simple_test.py ex3
python simple_test.py ex4
python simple_test.py ex5
python simple_test.py ex6
python simple_test.py ex7
python simple_test.py ex8
python simple_test.py ex9
